# Generated by Django 5.1.15 on 2026-02-22 21:08

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopyGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, help_text='Client-supplied session identifier for grouping requests.', max_length=64, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(64)])),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField(max_length=2000)),
                ('target_audience', models.CharField(max_length=300)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('urgent', 'Urgent'), ('witty', 'Witty'), ('inspirational', 'Inspirational')], max_length=20)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('google_ad', 'Google Ad'), ('email_subject', 'Email Subject'), ('facebook', 'Facebook'), ('twitter', 'Twitter / X')], max_length=20)),
                ('variations', models.JSONField(default=list, help_text='List of {"copy": str, "persuasion_score": float} objects.')),
                ('model_used', models.CharField(default='gpt-4o', max_length=50)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', '-created_at'], name='generator_c_session_a66d6a_idx')],
            },
        ),
    ]
